// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewFilesS3 creates a new instance of FilesS3. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFilesS3(t interface {
	mock.TestingT
	Cleanup(func())
}) *FilesS3 {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &FilesS3{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// FilesS3 is an autogenerated mock type for the S3 type
type FilesS3 struct {
	mock.Mock
}

type FilesS3_Expecter struct {
	mock *mock.Mock
}

func (_m *FilesS3) EXPECT() *FilesS3_Expecter {
	return &FilesS3_Expecter{mock: &_m.Mock}
}

// DeleteObject provides a mock function for the type FilesS3
func (_mock *FilesS3) DeleteObject(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FilesS3_DeleteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObject'
type FilesS3_DeleteObject_Call struct {
	*mock.Call
}

// DeleteObject is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *FilesS3_Expecter) DeleteObject(ctx any, key any) *FilesS3_DeleteObject_Call {
	return &FilesS3_DeleteObject_Call{Call: _e.mock.On("DeleteObject", ctx, key)}
}

func (_c *FilesS3_DeleteObject_Call) Run(run func(ctx context.Context, key string)) *FilesS3_DeleteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FilesS3_DeleteObject_Call) Return(err error) *FilesS3_DeleteObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FilesS3_DeleteObject_Call) RunAndReturn(run func(ctx context.Context, key string) error) *FilesS3_DeleteObject_Call {
	_c.Call.Return(run)
	return _c
}

// GetObject provides a mock function for the type FilesS3
func (_mock *FilesS3) GetObject(ctx context.Context, key string) (io.ReadCloser, *string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 io.ReadCloser
	var r1 *string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, *string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *string); ok {
		r1 = returnFunc(ctx, key)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*string)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, key)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// FilesS3_GetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObject'
type FilesS3_GetObject_Call struct {
	*mock.Call
}

// GetObject is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *FilesS3_Expecter) GetObject(ctx any, key any) *FilesS3_GetObject_Call {
	return &FilesS3_GetObject_Call{Call: _e.mock.On("GetObject", ctx, key)}
}

func (_c *FilesS3_GetObject_Call) Run(run func(ctx context.Context, key string)) *FilesS3_GetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FilesS3_GetObject_Call) Return(readCloser io.ReadCloser, s *string, err error) *FilesS3_GetObject_Call {
	_c.Call.Return(readCloser, s, err)
	return _c
}

func (_c *FilesS3_GetObject_Call) RunAndReturn(run func(ctx context.Context, key string) (io.ReadCloser, *string, error)) *FilesS3_GetObject_Call {
	_c.Call.Return(run)
	return _c
}

// PresignGetObject provides a mock function for the type FilesS3
func (_mock *FilesS3) PresignGetObject(ctx context.Context, key string, ttl time.Duration) (string, error) {
	ret := _mock.Called(ctx, key, ttl)

	if len(ret) == 0 {
		panic("no return value specified for PresignGetObject")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (string, error)); ok {
		return returnFunc(ctx, key, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) string); ok {
		r0 = returnFunc(ctx, key, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, key, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FilesS3_PresignGetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignGetObject'
type FilesS3_PresignGetObject_Call struct {
	*mock.Call
}

// PresignGetObject is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - ttl time.Duration
func (_e *FilesS3_Expecter) PresignGetObject(ctx any, key any, ttl any) *FilesS3_PresignGetObject_Call {
	return &FilesS3_PresignGetObject_Call{Call: _e.mock.On("PresignGetObject", ctx, key, ttl)}
}

func (_c *FilesS3_PresignGetObject_Call) Run(run func(ctx context.Context, key string, ttl time.Duration)) *FilesS3_PresignGetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FilesS3_PresignGetObject_Call) Return(s string, err error) *FilesS3_PresignGetObject_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *FilesS3_PresignGetObject_Call) RunAndReturn(run func(ctx context.Context, key string, ttl time.Duration) (string, error)) *FilesS3_PresignGetObject_Call {
	_c.Call.Return(run)
	return _c
}

// UploadObject provides a mock function for the type FilesS3
func (_mock *FilesS3) UploadObject(ctx context.Context, key string, body io.Reader, contentType string) error {
	ret := _mock.Called(ctx, key, body, contentType)

	if len(ret) == 0 {
		panic("no return value specified for UploadObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, string) error); ok {
		r0 = returnFunc(ctx, key, body, contentType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FilesS3_UploadObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadObject'
type FilesS3_UploadObject_Call struct {
	*mock.Call
}

// UploadObject is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - body io.Reader
//   - contentType string
func (_e *FilesS3_Expecter) UploadObject(ctx any, key any, body any, contentType any) *FilesS3_UploadObject_Call {
	return &FilesS3_UploadObject_Call{Call: _e.mock.On("UploadObject", ctx, key, body, contentType)}
}

func (_c *FilesS3_UploadObject_Call) Run(run func(ctx context.Context, key string, body io.Reader, contentType string)) *FilesS3_UploadObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *FilesS3_UploadObject_Call) Return(err error) *FilesS3_UploadObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FilesS3_UploadObject_Call) RunAndReturn(run func(ctx context.Context, key string, body io.Reader, contentType string) error) *FilesS3_UploadObject_Call {
	_c.Call.Return(run)
	return _c
}
