// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rvxt21/bucket-inventory/pkg/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewFilesDatabase creates a new instance of FilesDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFilesDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *FilesDatabase {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &FilesDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// FilesDatabase is an autogenerated mock type for the Database type
type FilesDatabase struct {
	mock.Mock
}

type FilesDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *FilesDatabase) EXPECT() *FilesDatabase_Expecter {
	return &FilesDatabase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type FilesDatabase
func (_mock *FilesDatabase) Create(ctx context.Context, file *dto.CreateFile) (*dto.File, error) {
	ret := _mock.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.CreateFile) (*dto.File, error)); ok {
		return returnFunc(ctx, file)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.CreateFile) *dto.File); ok {
		r0 = returnFunc(ctx, file)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.CreateFile) error); ok {
		r1 = returnFunc(ctx, file)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FilesDatabase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type FilesDatabase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - file *dto.CreateFile
func (_e *FilesDatabase_Expecter) Create(ctx any, file any) *FilesDatabase_Create_Call {
	return &FilesDatabase_Create_Call{Call: _e.mock.On("Create", ctx, file)}
}

func (_c *FilesDatabase_Create_Call) Run(run func(ctx context.Context, file *dto.CreateFile)) *FilesDatabase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.CreateFile
		if args[1] != nil {
			arg1 = args[1].(*dto.CreateFile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FilesDatabase_Create_Call) Return(file1 *dto.File, err error) *FilesDatabase_Create_Call {
	_c.Call.Return(file1, err)
	return _c
}

func (_c *FilesDatabase_Create_Call) RunAndReturn(run func(ctx context.Context, file *dto.CreateFile) (*dto.File, error)) *FilesDatabase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFile provides a mock function for the type FilesDatabase
func (_mock *FilesDatabase) DeleteFile(ctx context.Context, id string) (string, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FilesDatabase_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type FilesDatabase_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *FilesDatabase_Expecter) DeleteFile(ctx any, id any) *FilesDatabase_DeleteFile_Call {
	return &FilesDatabase_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, id)}
}

func (_c *FilesDatabase_DeleteFile_Call) Run(run func(ctx context.Context, id string)) *FilesDatabase_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FilesDatabase_DeleteFile_Call) Return(s string, err error) *FilesDatabase_DeleteFile_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *FilesDatabase_DeleteFile_Call) RunAndReturn(run func(ctx context.Context, id string) (string, error)) *FilesDatabase_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileByID provides a mock function for the type FilesDatabase
func (_mock *FilesDatabase) GetFileByID(ctx context.Context, id string) (*dto.File, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFileByID")
	}

	var r0 *dto.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*dto.File, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *dto.File); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FilesDatabase_GetFileByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileByID'
type FilesDatabase_GetFileByID_Call struct {
	*mock.Call
}

// GetFileByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *FilesDatabase_Expecter) GetFileByID(ctx any, id any) *FilesDatabase_GetFileByID_Call {
	return &FilesDatabase_GetFileByID_Call{Call: _e.mock.On("GetFileByID", ctx, id)}
}

func (_c *FilesDatabase_GetFileByID_Call) Run(run func(ctx context.Context, id string)) *FilesDatabase_GetFileByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FilesDatabase_GetFileByID_Call) Return(file *dto.File, err error) *FilesDatabase_GetFileByID_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *FilesDatabase_GetFileByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*dto.File, error)) *FilesDatabase_GetFileByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type FilesDatabase
func (_mock *FilesDatabase) List(ctx context.Context) ([]dto.File, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []dto.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]dto.File, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []dto.File); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FilesDatabase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type FilesDatabase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *FilesDatabase_Expecter) List(ctx any) *FilesDatabase_List_Call {
	return &FilesDatabase_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *FilesDatabase_List_Call) Run(run func(ctx context.Context)) *FilesDatabase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FilesDatabase_List_Call) Return(files []dto.File, err error) *FilesDatabase_List_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *FilesDatabase_List_Call) RunAndReturn(run func(ctx context.Context) ([]dto.File, error)) *FilesDatabase_List_Call {
	_c.Call.Return(run)
	return _c
}
